=== Starlight-Skull/seasonfall/source/worlds/_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "properties": {
      "type": "object",
      "properties": {
        "rootX": {
          "type": "number"
        },
        "rootY": {
          "type": "number"
        },
        "borderX": {
          "type": "number"
        },
        "borderY": {
          "type": "number"
        },
        "borderW": {
          "type": "number"
        },
        "borderH": {
          "type": "number"
        }
      },
      "required": [
        "rootX",
        "rootY",
        "borderX",
        "borderY",
        "borderW",
        "borderH"
      ]
    },
    "entities": {
      "type": "array"
    },
    "background": {
      "type": "array"
    },
    "foreground": {
      "type": "array"
    }
  },
  "required": [
    "properties",
    "entities",
    "background",
    "foreground"
  ]
}

=== Starlight-Skull/seasonfall/source/worlds/test.world.json
{
  "$schema": "./_schema.json",
  "properties": {
    "rootX": 8,
    "rootY": 6,
    "borderX": -10,
    "borderY": -10,
    "borderW": 40,
    "borderH": 30
  },
  "entities": [],
  "background": [
    [],
    [],
    [],
    [],
    [ "", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall", "brick_wall" ],
    [ "", "brick_wall", "brick_wall", "", "", "", "", "", "", "", "", "", "brick_wall", "brick_wall" ],
    [ "", "", "", "", "", "", "", "", "", "", "", "", "", "brick_wall" ],
    [ "", "", "", "", "", "", "", "", "", "", "", "", "", "brick_wall" ]
  ],
  "foreground": [
    [],
    [],
    [],
    [ "brick", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "plank:c-top", "brick" ],
    [ "brick", "plank:c-top", "", "", "", "", "", "", "", "", "", "", "", "", "brick" ],
    [ "brick", "plank:c-top", "", "", "", "", "", "", "", "", "", "", "", "", "brick" ],
    [ "brick", "plank:c-top", "", "", "door:m", "door", "", "", "", "", "", "", "", "", "brick" ],
    [ "brick", "plank:c-top", "", "", "", "", "", "", "", "", "", "", "", "", "brick" ],
    [ "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick", "brick" ]
  ]
}
